### ISSUE TITLE
Broken against latest oobabooga changes

### ISSUE THREAD

**Issue by chrisbennight** [TheBlokeAI/dockerLLM#8]
Oobabooga has moved to exllamav2 0.0.7(https://github.com/oobabooga/text-generation-webui/blob/main/requirements.txt#L5),  and uses classes  ( https://github.com/oobabooga/text-generation-webui/blob/main/modules/exllamav2.py#L9 for instance ) which are not present in the version baked into the image in dockerhub.

Ooba also moved to cuda 12.1 from 11.8m- https://github.com/oobabooga/text-generation-webui/commit/3345da2ea49a0469013cff22b6b6fc2073fd48be , which prevents a pip install of requirements.txt without updating the base cuda image

**Comment by TheBloke** [comment]
OK thanks for the report, I'll do a rebuild after dinner

**Comment by GeoffMillerAZ** [comment]
@TheBloke , I think it's missing the `sse_starlette` module too.

```
2023-11-07 01:55:43 ERROR:Failed to load the extension "openai".
Traceback (most recent call last):
  File "/workspace/text-generation-webui/modules/extensions.py", line 36, in load_extensions
    exec(f"import extensions.{name}.script")
  File "<string>", line 1, in <module>
  File "/workspace/text-generation-webui/extensions/openai/script.py", line 22, in <module>
    from sse_starlette import EventSourceResponse
ModuleNotFoundError: No module named 'sse_starlette'
```

**Comment by TheBloke** [comment]
OK I've updated the container to use CUDA 12.1.1 and rebuilt textgen. It seems to work OK with ExLlama v2 now:
![image](https://github.com/TheBlokeAI/dockerLLM/assets/784313/b5639524-bcda-45ba-b76e-079cdce95f0e)

Note that the oneclick container is still called `cuda11.8.0-ubuntu22.04-oneclick` despite it now actually being CUDA 12.1.1. This is unfortunate, but I can't change the name without also getting in touch with Runpod to update their template to point to a new name.

I will try to do that this week.

The names of the intermediate `pytorch` and `textgen` containers are updated to correctly show they now use CUDA 12.1.1.

Please let me know if there's any further issues.

**Comment by MattiPaivike** [comment]
FYI: The API example links are now broken since the update: https://github.com/TheBlokeAI/dockerLLM/blob/35b89eb15f7abc395b7976fc4aba373ef3ffcb97/README_Runpod_LocalLLMsUIandAPI.md?plain=1#L88
It seems they changed the API to: https://github.com/oobabooga/text-generation-webui/blob/main/docs/12%20-%20OpenAI%20API.md

**Comment by chrisbennight** [comment]
Can confirm it worked for me in runpod, thanks!  (your containers tend to be locally cached already, vs a fork, saving about 5 min of startup time)

**Comment by TheBloke** [comment]
@chrisbennight  thanks for confirming

@MattiPaivike thank you, I've updated the README links.

I've also just done another release, which updates the API CLI argument to `--extensions openai ` as per the deprecation of the old API.

**Comment by MarceloEmmerich** [comment]
I deployed a RunPod with the latest "with API" template, but keep getting a 404 when trying to access port 5000 from the "Connect" UI of RunPod or from my code. Also not sure if the new ```--extensions openai``` flag still requires me to click to enable "openai" in the "Session" section of the text Generation UI?

**Comment by TheBloke** [comment]
Sorry I forgot to push the latest container to `latest`. It's now pushed, and should produce these logs:
```
Launching text-generation-webui with args: --listen --api --extensions openai
2023-11-12 10:18:20 WARNING:
You are potentially exposing the web UI to the entire internet without any access password.
You can create one with the "--gradio-auth" flag like this:

--gradio-auth username:password

Make sure to replace username:password with your own.
2023-11-12 10:18:24 INFO:Loading the extension "openai"...
2023-11-12 10:18:24 INFO:OpenAI compatible API URL:

http://0.0.0.0:5000/v1

INFO:     Started server process [92]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:5000 (Press CTRL+C to quit)
2023-11-12 10:18:24 WARNING:
The current API is deprecated and will be replaced with the OpenAI compatible API on November 13th.
To test the new API, use "--extensions openai" instead of "--api".
For documentation on the new API, consult:
https://github.com/oobabooga/text-generation-webui/wiki/12-%E2%80%90-OpenAI-API
2023-11-12 10:18:24 INFO:Streaming API URL:

ws://0.0.0.0:5005/api/v1/stream
```

**Comment by MarceloEmmerich** [comment]
Can confirm that the new container image is being pulled. However, there is still a port issue. Are ```--api``` and ```--extensions openai``` exclusive? In the "Sessions" section of the UI the "openai" and the "api" boxes are both ticked as default...

```2023-11-12 10:42:33 WARNING:
2023-11-12T10:42:33.794039991Z The current API is deprecated and will be replaced with the OpenAI compatible API on November 13th.
2023-11-12T10:42:33.794043791Z To test the new API, use "--extensions openai" instead of "--api".
2023-11-12T10:42:33.794046781Z For documentation on the new API, consult:
2023-11-12T10:42:33.794049211Z https://github.com/oobabooga/text-generation-webui/wiki/12-%E2%80%90-OpenAI-API
2023-11-12T10:42:33.795881757Z 2023-11-12 10:42:33 INFO:Streaming API URL: 
2023-11-12T10:42:33.795889577Z 
2023-11-12T10:42:33.795892067Z ws://0.0.0.0:5005/api/v1/stream
2023-11-12T10:42:33.795895037Z 
2023-11-12T10:42:33.855678001Z 2023-11-12 10:42:33 INFO:Loading the extension "gallery"...
2023-11-12T10:42:33.857142305Z 2023-11-12 10:42:33 INFO:Blocking API URL: 
2023-11-12T10:42:33.857162675Z 
2023-11-12T10:42:33.857166445Z http://0.0.0.0:5000/api
2023-11-12T10:42:33.857170385Z 
2023-11-12T10:42:33.936977088Z INFO:     Started server process [66]
2023-11-12T10:42:33.937005508Z INFO:     Waiting for application startup.
2023-11-12T10:42:33.947766490Z INFO:     Application startup complete.
2023-11-12T10:42:33.966132744Z ERROR:    Traceback (most recent call last):
2023-11-12T10:42:33.966144194Z   File "/usr/local/lib/python3.10/dist-packages/uvicorn/server.py", line 160, in startup
2023-11-12T10:42:33.966147934Z     server = await loop.create_server(
2023-11-12T10:42:33.966151264Z   File "uvloop/loop.pyx", line 1790, in create_server
2023-11-12T10:42:33.966155334Z OSError: [Errno 98] error while attempting to bind on address ('0.0.0.0', 5000): address already in use
2023-11-12T10:42:33.966160354Z ```

**Comment by TheBloke** [comment]
Please pull again, I just updated it again so it only runs `--extension openai`.

The reason why I wanted to do both is that there's a PR from oobabooga in text-generation-webui that's going to change the flag back to `--api`, I guess tomorrow. So I was hoping to avoid the need to update it back to `--api` again.  But given that running both args seems to cause that error, currently it just says `--extension openai`

I've pushed to `:latest` so please try testing again.

**Comment by MarceloEmmerich** [comment]
Works now, thanks!

**Comment by TheBloke** [comment]
Great, thanks for confirming
